const REGISTER = '/api/accounts/users/create/';
const LOGIN = '/api/accounts/token/obtain/';
const HOMEPOSTSLIST = '/api/posts/list/';
const CREATEPOST = '/api/posts/postcreate/';
const GETUSERPROFILE = '/api/profile/';
const GETUSERPROFILEPOSTS = '/api/profile/posts/';
const POSTLIKE = '/api/posts/list/like/';
const ADDCOMMENT = '/api/posts/comments/';
const LOGOUT='/api/accounts/logout/';